plugins {
    id 'com.android.application'
    id 'com.android.legacy-kapt'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.actia.myapplication'
    compileSdk 37

    defaultConfig {
        applicationId "com.actia.myapplication"
        minSdk 34
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        compose true
    }
}

dependencies {
    implementation 'androidx.test.espresso:espresso-idling-resource:3.7.0'
    implementation 'androidx.test.uiautomator:uiautomator:2.4.0'


    // ============================================================
    // Compose
    // ============================================================

    def composeBom = platform('androidx.compose:compose-bom:2026.06.00')

    implementation composeBom
    androidTestImplementation composeBom

    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.foundation:foundation-layout'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-core'
    implementation 'androidx.compose.runtime:runtime'
    implementation 'androidx.compose.runtime:runtime-livedata'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3.adaptive:adaptive'

    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'

    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'

    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.11.0'


    // ============================================================
    // AndroidX
    // ============================================================

    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    def lifecycle_version = "2.6.2"

    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"


    // ============================================================
    // Navigation
    // ============================================================

    implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.5.3'
    implementation 'androidx.navigation:navigation-runtime-ktx:2.9.8'


    // ============================================================
    // Espresso / Android Instrumentation Tests
    // ============================================================

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test:rules:1.7.0'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-idling-resource:3.7.0'


    // ============================================================
    // JUnit
    // ============================================================

    testImplementation 'junit:junit:4.13.2'


    // ============================================================
    // Retrofit
    // ============================================================

    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-scalars:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'


    // ============================================================
    // OkHttp
    // ============================================================

    implementation 'com.squareup.okhttp3:okhttp:5.5.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.5.0'


    // ============================================================
    // MockWebServer
    // ============================================================

    androidTestImplementation 'com.squareup.okhttp3:mockwebserver3:5.5.0'

    androidTestImplementation(
            'com.squareup.retrofit2:converter-simplexml:3.0.0'
    ) {
        exclude group: 'stax', module: 'stax-api'
        exclude group: 'stax', module: 'stax'
        exclude group: 'xpp3', module: 'xpp3'
    }

    testImplementation 'com.squareup.okhttp3:mockwebserver3:5.5.0'

    testImplementation(
            'com.squareup.retrofit2:converter-simplexml:3.0.0'
    ) {
        exclude group: 'stax', module: 'stax-api'
        exclude group: 'stax', module: 'stax'
        exclude group: 'xpp3', module: 'xpp3'
    }


    // ============================================================
    // Coroutines
    // ============================================================

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3'


    // ============================================================
    // Koin
    // ============================================================

    ext.koin_version = '4.2.2'

    implementation "io.insert-koin:koin-core:$koin_version"
    implementation "io.insert-koin:koin-compose-viewmodel:$koin_version"
    implementation "io.insert-koin:koin-androidx-compose:$koin_version"
    implementation "io.insert-koin:koin-compose-viewmodel-navigation:$koin_version"

    testImplementation "io.insert-koin:koin-test:$koin_version"
    androidTestImplementation "io.insert-koin:koin-test:$koin_version"

    testImplementation 'org.hamcrest:hamcrest:3.0'
    androidTestImplementation 'org.hamcrest:hamcrest:3.0'


    // ============================================================
    // Picasso
    // ============================================================

    ext.picassa_version = '2.8'

    implementation "com.squareup.picasso:picasso:$picassa_version"


    // ============================================================
    // MockK
    // ============================================================

    testImplementation 'io.mockk:mockk:1.12.0'
}